### ISSUE TITLE
Describe goal

### ISSUE THREAD

**Issue by Beanow** [sfosc/wizard#1]
I'm thinking something along the lines of:

> # Goal
> This wizard is intended to be an **educational journey** through the major themes you will need to consider when trying to build a Sustainable Free and Open Source Community of your own.
> We'll provide **context and further reading** for each of these themes to help in this journey.
>
> The output of the wizard will be a set of documents that you can use directly for the project, for example a software license, [social contract](https://sfosc.org/social-contracts/), [code of conduct](https://github.com/sfosc/sfosc/blob/master/CODE_OF_CONDUCT.md) and so on.
>
> The wizard _will not aim to be neutral_ in any way, but should reflect SFOSC principles and community views.

**Comment by nothingismagick** [comment]
If it didn't sound so familiar to the discussion we had at the discord server, I would be thoroughly impressed with how awesome it sounds. Love it!

**Comment by Beanow** [comment]
For the repository description, maybe this?

> An educational wizard for creating your own SFOSC

**Comment by nothingismagick** [comment]
Great.
