### ISSUE TITLE
Is this for the greater good?

### ISSUE THREAD

**Issue by nothingismagick** [sfosc/wizard#8]
If so we should add this to the README
[![Greater-Good Affirmation](https://good-labs.github.io/greater-good-affirmation/assets/images/badge.svg)](https://good-labs.github.io/greater-good-affirmation)
```
[![Greater-Good Affirmation](https://good-labs.github.io/greater-good-affirmation/assets/images/badge.svg)](https://good-labs.github.io/greater-good-affirmation)
```

**Comment by Beanow** [comment]
I love the Greater-Good Affirmation and I believe it can work complimentary to the current SFOSC social contract.

However `As a representative of an open source project or group, I affirm that the community to which I belong makes a best effort to exist for the greater good.` this speaks for the community intention and I think that should be done only with enough of a chance for the community to share their thoughts on it.

Let's bring that up to the main repository and ask the members.
If (/ when) approved we should apply it across the sfosc org in my opinion.

**Comment by nothingismagick** [comment]
Yes i totally agree. That project needs more visibility. :)

**Comment by Beanow** [comment]
On the main repo GGA has been approved for SFOSC, and I believe that applies to here as well. Let's add it.
